#!/bin/sh
NAME=$(git branch | grep '*' | sed 's/* //')

if [ ! $NAME ]
then
	NAME='(empty branch)'
fi

echo "Running pre-push hook on $NAME"

# Don't run on rebase
if [ "$NAME" != "(no branch)" ]
then

	CHANGES=$(git diff --numstat | wc -l)
	CACHED_CHANGES=$(git diff --cached --numstat | wc -l)
	TOTAL_CHANGES=$(($CHANGES + $CACHED_CHANGES))

	if [ $TOTAL_CHANGES -ne "0" ]
	then
		echo "Stashing changes..."
		git stash save -k -u
		echo "Changes stashed"
	fi

	npm test

	RETVAL=$?

	if [ $TOTAL_CHANGES -ne "0" ]
	then
		echo "Restoring stash..."
		git stash pop -q
		echo "Stash restored"
	fi

	if [ $RETVAL -ne 0 ]
	then
		echo "Pre-push hook failed"
		exit $RETVAL
	fi

	echo "Pre-push hook succeeded"
fi
